#!/bin/sh

# To generate PDFs that are somewhat OK you will need to have the Roboto and Roboto mono font families installed on your system
# https://fonts.google.com/specimen/Roboto
# https://fonts.google.com/specimen/Roboto+Mono

echo "-----Rebuilding documentation..."

echo "     >>> HTML (documentation/)"

echo "     > index.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/index.md -o documentation/index.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > allah.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/allah.md -o documentation/allah.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > differentpattern.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/differentpattern.md -o documentation/differentpattern.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > spanning.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/spanning.md -o documentation/spanning.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > faq.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/faq.md -o documentation/faq.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > shl_features.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/shl_features.md -o documentation/shl_features.html --lua-filter=documentation/source/pandocfilters/filter-html.lua

echo "     >>> PDF (documentation/pdf/)"
mkdir -p documentation/source/pdftemp

echo "     > index.html > index.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/index.md -o documentation/source/pdftemp/index.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/index.html documentation/pdf/index.pdf
echo "     > spanning.html > spanning.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/spanning.md -o documentation/source/pdftemp/spanning.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/spanning.html documentation/pdf/spanning.pdf
echo "     > faq.html > faq.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/faq.md -o documentation/source/pdftemp/faq.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/faq.html documentation/pdf/faq.pdf
echo "     > shl_features.html > shl_features.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/shl_features.md -o documentation/source/pdftemp/shl_features.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
# weasyprint does not currently handle "ky" or "wo" langauge tags, but requires three-letter tags instead:
sed -i -e s/lang=\"wo\"/lang=\"WLF\"/ -e s/lang=\"ky\"/lang=\"kir\"/   documentation/source/pdftemp/shl_features.html
weasyprint documentation/source/pdftemp/shl_features.html documentation/pdf/shl_features.pdf
echo "     > allah.html > allah.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/allah.md -o documentation/source/pdftemp/allah.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/allah.html documentation/pdf/allah.pdf
echo "     > differentpattern.html > differentpattern.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/differentpattern.md -o documentation/source/pdftemp/differentpattern.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/differentpattern.html documentation/pdf/differentpattern.pdf

echo "     >>> Product site (documentation/)"
echo "     > faq.md"
python3 documentation/source/makepsmd.py documentation/source/faq.md documentation/source/productsite/faq.md -q


echo "-----Completed!"
