s/_post_lam_med_small_fina/_fina_post_lam_med_small/g
s/_post_lam_ini_small_fina/_fina_post_lam_ini_small/g
s/_post_lam_ini_fina/_fina_post_lam_ini/g
s/_post_lam_med_fina/_fina_post_lam_med/g
s/_warsh_fina/_fina_warsh/g
s/_small_fina/_fina_small/g
s/_pre_alef_warsh_init/_init_pre_alef_warsh/g
s/_pre_alef_medi/_medi_pre_alef/g
s/_pre_alef_init/_init_pre_alef/g
s/_sindhi_fina/_fina_sindhi/g
s/_knotted_flat_fina/_fina_knotted_flat/g
s/_knotted_high_fina/_fina_knotted_high/g
s/_knotted_high_medi/_medi_knotted_high/g
s/_hooked_fina/_fina_hooked/g
s/_hooked_medi/_medi_hooked/g
s/_hooked_init/_init_hooked/g
s/_filled_fina/_fina_filled/g
s/_allah_fina/_fina_allah/g
s/_allah1_init/_init_allah1/g
s/_allah1_medi/_medi_allah1/g
s/_allah2_medi/_medi_allah2/g